### ISSUE TITLE
Thread block when using a high flush.size

### ISSUE THREAD

**Issue by mavdi** [confluentinc/kafka-connect-storage-cloud#107]
I'm setting up a Kafka connect S3 sink with the following configuration 

```
{
    "name": "kafka-s3-sink",
    "config": {
    	"tasks.max": 5,
    	"format.class": "io.confluent.connect.s3.format.json.JsonFormat",
        "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    	"topics": "example-topic",
    	"flush.size": 100000,
    	"storage.class": "io.confluent.connect.s3.storage.S3Storage",
    	"schema.compatibility": "NONE",
    	"s3.bucket.name": "foo",
        "s3.region": "us-east-1",
    	"s3.part.size": 5242880,
    	"rotate.interval.ms": 86400000,
        "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
        "partition.duration.ms": 3600000,
	"locale": "en",
	"timezone": "UTC",
	"path.format": "YYYY-MM-dd-HH-mm-ss",
	"schema.generator.class": "io.confluent.connect.storage.hive.schema.TimeBasedSchemaGenerator"
    }
```

When setting `flush.size` to about `10000` everything works. But any number greater than that, seems to hang the connector altogether. I'm saying this because I get the following error:

```
[2017-10-17 11:05:46,812] WARN failed to publish monitoring message (io.confluent.monitoring.clients.interceptor.MonitoringInterceptor)
org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:499)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:440)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:360)
	at io.confluent.monitoring.clients.interceptor.MonitoringInterceptor.publishMonitoringMessage(MonitoringInterceptor.java:255)
	at io.confluent.monitoring.clients.interceptor.MonitoringInterceptor.publishMetrics(MonitoringInterceptor.java:240)
	at io.confluent.monitoring.clients.interceptor.MonitoringInterceptor.publishMetrics(MonitoringInterceptor.java:206)
	at io.confluent.monitoring.clients.interceptor.MonitoringInterceptor.run(MonitoringInterceptor.java:160)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at org.apache.kafka.clients.Metadata.awaitUpdate(Metadata.java:156)
	at org.apache.kafka.clients.producer.KafkaProducer.waitOnMetadata(KafkaProducer.java:548)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:450)
```

Is this a known issue? Any workarounds?

**Comment by kkonstantine** [comment]
Hi @mavdi 

at a first glance, this seems to be an issue with monitoring interceptors and not with the S3 connector itself. 

- Does data export to S3 work without interceptors for this particular flush size?
- Can you give a bit more information regarding your deployment or include more related logs? Is this used with Confluent Control Center? The issue seems to be that the interceptor wasn't able to publish monitoring messages.

**Comment by kkonstantine** [comment]
And some additional information: 

- You may configure your interceptor's producer by prefixing its properties as mentioned here: https://docs.confluent.io/current/control-center/docs/clients.html#configuration-options
- Your interceptor must be closing abruptly because the connector's consumer is closing unexpectedly. Thus, we'd need more logs to begin with. 
- Again, it'd be good to know if you can export at this `flush.size` without interceptors. 
- You might need to increase the verbosity of the log level (set to `debug` or `trace`, focus on specific loggers by keeping some irrelevant loggers to `info` or `debug` levels).

**Comment by mavdi** [comment]
I've removed the interceptors and it seems to have allowed me to increase `flush.size` to `40000`.

Anything beyond that still fails. I get a strange error:

```
 WARN Commit of WorkerSinkTask{id=kafka-s3-sink-time20-0} offsets timed out
```
- Not using Confluent Control Center

**Comment by mavdi** [comment]
Again, hit and miss kind of errors. I can't make any concise picture of what's going on..
```
[2017-10-18 09:29:18,749] WARN Aborting multi-part upload with id 'z5wjp1k4gZvSEHiGAh3OQC_bhI9CUOybf8x._xvuWtOqOOkgc8gVeX1h3AEUrlgjWLQHe9.GXAI9OKrx3jwV72xNgV9vzGXu0R83IughQLs9gdbWU19BTQatOg9QEsUazu_V1H8B37ncZtKNhyMgp77wk1TJ2dWGYUUmIDdFByo-' (io.confluent.connect.s3.storage.S3OutputStream)
```

**Comment by kkonstantine** [comment]
A higher `flush.size` is definitely attainable by the connector. Aborts of multi-part uploads might be more related to connectivity issues. Tuning `s3.part.size` could help diagnose such issue for different sizes. Closing because it's been a while since this issue was discussed, but feel free to re-open if it remains an issue.

**Comment by sxganapa** [comment]
My pipeline works if I set the flush size to 1 but if I set to high value(even to 1000) I am missing data. I have only 7000 records as input. If I set to a high value it is missing about 1000 records. what should I do to fix this. This is my configuration.



{                                                                                                                                                                                                                                                                   
  "name": "meetups-to-s3_new",                                                                                                                                                                                                                                          
  "config": {                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                    
    "_comment": "The S3 sink connector class",                                                                                                                                                                                                                      
    "connector.class":"io.confluent.connect.s3.S3SinkConnector",                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                    
    "_comment": "The total number of Connect tasks to spawn (with implicit upper limit the number of topic-partitions)",                                                                                                                                            
    "tasks.max":"10",                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                    
    "_comment": "Which topics to export to S3",                                                                                                                                                                                                                     
    "topics":"AttachmentFeed",                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                    
    "_comment": "The S3 bucket that will be used by this connector instance",                                                                                                                                                                                       
    "s3.bucket.name":"jab-s3-message", 
                                                                                                                                                                                                                                                                    
    "_comment": "The AWS region where the S3 bucket is located",                                                                                                                                                                                                    
    "s3.region":"us-east-1",                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                    
    "_comment": "The size in bytes of a single part in a multipart upload. The last part is of s3.part.size bytes or less. This property does not affect the total size of an S3 object uploaded by the S3 connector",                                             
    "s3.part.size":"5242880",                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                    
    "_comment": "The maximum number of Kafka records contained in a single S3 object. Here a high value to allow for time-based partition to take precedence",                                                                                                                                                                              
    "flush.size":"1",                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                    
    "_comment": "Kafka Connect converter used to deserialize keys (unused in this example)",                                                                                                                                                                        
    "key.converter":"org.apache.kafka.connect.json.JsonConverter",                                                                                                                                                                                                  
    "key.converter.schemas.enable":"false",                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                    
    "_comment": "Kafka Connect converter used to deserialize values",                                                                                                                                                                                               
    "value.converter":"org.apache.kafka.connect.json.JsonConverter",                                                                                                                                                                                                
    "value.converter.schemas.enable":"false",                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                    
    "_comment": "The type of storage for this storage cloud connector",                                                                                                                                                                                             
    "storage.class":"io.confluent.connect.s3.storage.S3Storage",                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                    
    "_comment": "The storage format of the objects uploaded to S3",                                                                                                                                                                                                 
    "format.class":"io.confluent.connect.s3.format.json.JsonFormat",                                                                                                                                                                                                
                                                                                                                                                                                                                                                                    
    "_comment": "Schema compatibility mode between records with schemas (Useful when used with schema-based converters. Unused in this example, listed for completeness)",                                                                                          
    "schema.compatibility":"NONE",                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                    
    "_comment": "The class used to partition records in objects to S3. Here, partitioning based on time is used.",                                                                                                                                                  
    "partitioner.class":"io.confluent.connect.storage.partitioner.TimeBasedPartitioner",                                                                                                                                                                            
                                                                                                                                                                                                                                                                    
    "_comment": "The locale used by the time-based partitioner to encode the date string",                                                                                                                                                                          
    "locale":"en",
    
    "_comment": "Setting the timezone of the timestamps is also required by the time-based partitioner",                                                                                                                                                            
    "timezone":"UTC",                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                    
    "_comment": "The date-based part of the S3 object key",                                                                                                                                                                                                         
    "path.format":"'date'=YYYY-MM-dd/'hour'=HH",                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                    
    "_comment": "The duration that aligns with the path format defined above",                                                                                                                                                                                      
    "partition.duration.ms":"3600000",                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                    
    "_comment": "The interval between timestamps that is sufficient to upload a new object to S3. Here a small interval of 1min for better visualization during the demo",                                                                                          
    "rotate.interval.ms":"60000",                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                    
    "_comment": "The class to use to derive the timestamp for each record. Here Kafka record timestamps are used",                                                                                                                                                  
    "timestamp.extractor":"Record"                                                                                                                                                                                                                                  
  }                                                                                                                                                                                                                                                                 
}
