### ISSUE TITLE
Using jdbc sink connector to write into different schemas

### ISSUE THREAD

**Issue by ismail261** [confluentinc/kafka-connect-storage-cloud#122]
Hi,

I am using jdbc sink connector to insert data into different schema.
But it keeps on saying table name is missing.

Below is the property that i use:
"table.name.format": "schema.application"

If i do not give schema name then it inserts into public schema.

Am i doing anything wrong here? Is there a way to specify schema name?

**Comment by kkonstantine** [comment]
I believe this issue belongs to JDBC Connector's repo.
Allow me to close this ticket. Please feel free to reopen here: 
https://github.com/confluentinc/kafka-connect-jdbc
