### ISSUE TITLE
Add support for GCS

### ISSUE THREAD

**Issue by PierreC1024** [confluentinc/kafka-connect-storage-cloud#127]
Do you plan to add support for GCS soon ?

**Comment by siamak-haschemi** [comment]
We are also interested in this, as we moved from Azure to GCP, and introduced Kafka.

**Comment by kkonstantine** [comment]
No ETA yet, but feel free to track the progress of this PR here: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/128

**Comment by rmoff** [comment]
See https://www.confluent.io/connector/kafka-connect-gcs/

**Comment by kkonstantine** [comment]
Indeed, Confluent's GCS connector is now generally available (GA version) in Confluent Hub here: 

https://www.confluent.io/hub/
