### ISSUE TITLE
BufferOverflowException in S3OutputStream

### ISSUE THREAD

**Issue by staslos** [confluentinc/kafka-connect-storage-cloud#141]
There is two overloaded versions of `write` method on S3OutputStream. In situation when stream `buffer` becomes full by calling `public void write(byte[] b, int off, int len)`, and then `public void write(int b)` called for some reason, we'll get BufferOverflowException. 

To avoid it, we need to do a check `!buffer.hasRemaining()` in both methods before returning and flushing buffer if it's full.

Just to provide more context, I got this exception when extending `kafka-connect-s3` with custom format that uses LZOP compression before sending data to S3. In this case LZOP API finalizes compression of the chunk of data by writing a byte at the end of the S3 stream. If buffer of the stream is full by that time, I get BufferOverflowException. To be consistent, both methods now check if buffer is full before returning.

There is test that supports given idea.

See PR for this issue [PR-140](https://github.com/confluentinc/kafka-connect-storage-cloud/pull/140)

**Comment by kkonstantine** [comment]
Fixed by: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/140

Thanks @staslos
