### ISSUE TITLE
AWS Credentials per connector

### ISSUE THREAD

**Issue by javierholguera** [confluentinc/kafka-connect-storage-cloud#142]
Hi,

We are deploying multiple connectors to our Kafka Connect cluster. Some of them move more sensitive than others, which means that they will send the data to different S3 buckets with various security levels and separate sets of credentials.

AFAIK it is only possible to configure the client_id and secret_key based on one of these mechanisms:

AWS credentials provider chain that looks for credentials in this order:

- Environment Variables - AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY (RECOMMENDED since they are recognized by all the AWS SDKs and CLI except for .NET), or AWS_ACCESS_KEY and AWS_SECRET_KEY (only recognized by Java SDK)
- Java System Properties - aws.accessKeyId and aws.secretKey
Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
- Credentials delivered through the Amazon EC2 container service if AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" environment variable is set and security manager has permission to access the variable,
- Instance profile credentials delivered through the Amazon EC2 metadata service

We have used the first option so far, but now we face the need for a more "connector-level" configuration values for the credentials. Something like:

```json
    "config": {
        "connector.class": "io.confluent.connect.s3.S3SinkConnector",
        "s3.bucket.name": "zopa-kafka-debug-logs",
        "s3.client_id": "my-client-id",
        "s3.secret_value": "my-secret"
  }
```

Is this possible in any way?

**Comment by cddr** [comment]
We have this problem too. I think it can be solved by writing your own `com.amazonaws.auth.AWSCredentialsProvider`, and include in each job a reference to some secret id that you can use to lookup the secret in whatever you're using to store them (e.g. vault).

```
"config": {
        "connector.class": "io.confluent.connect.s3.S3SinkConnector",
        "s3.credentials.provider.class": "MySecretProvider",
        "secret.id": "s3-debug-logs",
        "s3.bucket.name": "zopa-kafka-debug-logs"
  }
```

Probably not a great idea to put the secret itself in the config because that gets written to the config topic which is then made available by the REST API.

**Comment by javierholguera** [comment]
@cddr _that ship has already sailed_, the JDBC connector [takes the DB connection credentials](https://docs.confluent.io/current/connect/connect-jdbc/docs/source_config_options.html) as configuration for the connector.

We have blacklisted any call to the API from anything apart from the deployment pipeline responsible for creating the connectors, as a protection.

I've thought about a custom implementation for `AWSCredentialsProvider` too, but I'm a bit hesitant because we rely on injecting configuration into applications as a principle versus applications looking for their configuration. Implementing a Vault provider fees like the later.

**Comment by kkonstantine** [comment]
This capability has been added with: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/156

Still a custom credentials provider is required. A very simple example is given in the tests of this PR. Its meant for demonstration purposes only. Please use a similar clas after you assess it conforms with your environment's security requirements. 

Closing this ticket, but feel free to reopen if you think there are still gaps in enabling this approach.

**Comment by tribeclickgh** [comment]
Hi @kkonstantine , i believe that solution is not ideal, since one of the key benefits (in my opinion) of kafka-connect is that you get a full array of connectors without having to touch java code. 

Is there any way to specify the credentials per connector either using a .properties file or via the rest api?

**Comment by DaveSlinn** [comment]
+1 with @tribeclickgh comment that if you have to write your own java class, a large portion of the benefit of using kafka connectors is lost.
