### ISSUE TITLE
Failed to resume TopicPartition from NON-AWS S3

### ISSUE THREAD

**Issue by chtiouiha** [confluentinc/kafka-connect-storage-cloud#146]
We are trying to store our data from kafka to our custom s3 (non-AWS)
but the S3SinkTask returns:
> ConnectException: "Failed to resume TopicPartition from S3"
> Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: f8be3bf7-ce62-4e02-8b0c-54ad3a7361b1), S3 Extended Request ID: null

Is it possible in any way to sink with local storage s3?

this is my s3-sink properties file:
>name=s3-sink
>connector.class=com.deviantart.kafka_connect_s3.S3SinkConnector
>tasks.max=1
>s3.endpoint=https://xxxxxxxxxxxxxxxxxx
>topics=xxxxx
>group.id=test_002
>s3.bucket=s3://xxxxxxxxx
>s3.path_style=false
>local.buffer.dir=/tmp/kafka

**Comment by cricket007** [comment]
Different connector. Might want to post issue there. https://github.com/DeviantArt/kafka-connect-s3/issues

**Comment by kkonstantine** [comment]
@chtiouiha closing issue as non-relevant to this connector
