### ISSUE TITLE
schema.generator.class property not documented

### ISSUE THREAD

**Issue by jocelyndrean** [confluentinc/kafka-connect-storage-cloud#147]
Hi all,
I checked the _Quickstart_ section in the documentation. In this example properties file `etc/kafka-connect-s3/quickstart-s3.properties` ([here](https://github.com/confluentinc/kafka-connect-storage-cloud/blob/master/kafka-connect-s3/config/quickstart-s3.properties)), there is a property:

`schema.generator.class=io.confluent.connect.storage.hive.schema.TimeBasedSchemaGenerator`

But, I didn't find informations about `schema.generator.class` property in the [documentation](https://docs.confluent.io/current/connect/connect-storage-cloud/kafka-connect-s3/docs/configuration_options.html).

Maybe this is a legacy property.

**Comment by kkonstantine** [comment]
Indeed, this property has been deprecated but its trace has remained in the quickstart. Closing since https://github.com/confluentinc/kafka-connect-storage-cloud/pull/203 will be merged soon
