### ISSUE TITLE
Timestamp question

### ISSUE THREAD

**Issue by linckye** [confluentinc/kafka-connect-storage-cloud#154]
After downloading from the official website and running directly, no configuration has been modified.
Using JdbcSourceConnect - S3SinkConnect.
Found that the timestamp field in the original table is all converted into milliseconds.
But what I really need is a timestamp format.

**Comment by kkonstantine** [comment]
This connector (S3) does not mutate any fields, including timestamps in the Kafka record or a record field. When timebased partitioning is used, it uses the timestamp value to apply partitioning. But again this value remains unchanged. 

Please create an issue in https://github.com/confluentinc/kafka-connect-jdbc with a few more details if this remains an issue for your setup. 

Closing here.
