### ISSUE TITLE
Data Reprocessing, reset offset

### ISSUE THREAD

**Issue by Patafix** [confluentinc/kafka-connect-storage-cloud#162]
Hello everyone,

I want to use this connector as a backup of my kafka where the retention is infinite.

Everything works fine now, but it does not replay every kafka messages from start, I do not know how kafka-connect choose the offset or if we can set the offset.
Can you help me find out?

If kafka-connect crash for a long period what happend ?

**Comment by cricket007** [comment]
You would reset the offset for the consumer group.
