### ISSUE TITLE
S3_Sink connector works with Oracle Object Storage

### ISSUE THREAD

**Issue by venkat50** [confluentinc/kafka-connect-storage-cloud#167]
I was able to verify s3-sink could be configured to support Oracle Object Storage leveraging [Amazon S3 compatibility API](https://docs.us-phoenix-1.oraclecloud.com/Content/Object/Tasks/s3compatibleapi.htm)

The two important properties to change are:
s3.region
store.url

Please note my testing was minimal.
Thanks,
Venkat

**Comment by rhauch** [comment]
Thanks for the feedback, @venkat50. Since this isn't an issue per se, I'm going to close this. If you feel it should not be closed, please reopen and provide more detail.

**Comment by venkat50** [comment]
Thank you, Randall. I wanted to report that it works. I guess my choice of using issue was incorrect. What is the correct forum/method for feedback/non-issues?

**Comment by rhauch** [comment]
If you want to just provide feedback or ask questions, consider the Confluent Slack community or discussion group (see middle of the https://www.confluent.io/contact/ page).

Another approach might be to change wording in the issue to say what you're asking/suggesting change. For example, "Docs should show example of using Oracle Object Storage", or "Add example showing use of Oracle Object Storage". Ideally, the more specific the suggestion the better. Of course the most helpful is to then submit a PR with the suggested improvements/clarifications to the docs or code.

**Comment by venkat50** [comment]
Thank you for the detailed clarification with examples. Very much
appreciated.

I am now  in process of testing HDFS connector....So far the experience has
been great and tutorials are easy to follow (being a newbie to kafka).

**Comment by kenkensonson** [comment]
Hi venkat50,

Cloud you tell me the procedure that you connected to Oracle Object Storage with S3-sink?

Regards,
Kenichi Sonoda

**Comment by venkat50** [comment]
confiHI Ken,

Apologize for the delayed response. I returned back from a long vacation.

The procedure is very simple. Oracle Object Storage is S3 Compatibile.
Using OCI Console, you can generate the auth token and secrets to update
the S3 sink configuration. You need to ensure the url is the correct format
to access the Oracle Object Storage.

I wanted to reply to you immediately and hope that information is helpful.
However, if you need to specific steps/sample configuration, let me know.

Thanks for your patience,
Venkat

**Comment by kenkensonson** [comment]
Hi  Venkat,

Thank you for your reply! I could manage to configure properly so far.
I hope you had a good vacation.😊

Regards,
Kenichi Sonoda

2019年7月17日(水) 8:58 Venkat Padmanabhan <notifications@github.com>:

**Comment by rishavch0421** [comment]
Hi Venkat, could you please share exactly which properties you set for the credentials? A sample config file would be really helpful
