### ISSUE TITLE
AWS SNS support for Kafka Connect

### ISSUE THREAD

**Issue by prawen** [confluentinc/kafka-connect-storage-cloud#174]
Hello,

Not sure if this is a valid question. Is there any way to use/integrate confluent with AWS SNS ? Basically, I want to send notifications using SNS. which I'm doing with gmail smtp and SMS gateway as of now.

**Comment by cricket007** [comment]
This project is for intended for storage into S3 at the moment. 

If you can write the Java code, then, yes you can integrate Kafka Connect API with any other technology (doesn't require Confluent packages). 

For example, [this project sends data to SQS](https://github.com/ConnectedHomes/sqs-kafka-connect). I'm sure there are examples somewhere for taking SQS data and pushing out SNS messages.

**Comment by kkonstantine** [comment]
The above comment is not particularly accurate @cricket007 

This repo is host of cloud storage connectors. Currently, S3 is hosted as open source. GCS connector has been released as proprietary connector available at [Confluent Hub](https://www.confluent.io/connector/kafka-connect-gcs/) 
from a separate repo, sharing common characteristics. 

@prawen , still an SNS integration is not obvious here or at least it hasn't been prioritized. I'll label this issue as an `enhancement`. Is there a specific use case, integration you are interested in with S3 specifically?

**Comment by cricket007** [comment]
Right, let me emphasize "storage", then, which SNS is not. 

It is possible to use AWS lambdas to notify SNS of files that S3 Connect writes, but that's outside the scope of this connect. We've used this pattern to convert Avro files into Parquet since Parquet file support isn't included

**Comment by aakashnshah** [comment]
Looks like this issue has been appropriately addressed, will close it now.

**Comment by aakashnshah** [comment]
Looks like the issue has been appropriately addressed, will close it now.
