### ISSUE TITLE
S3 Connector `close()` NullPointerException

### ISSUE THREAD

**Issue by atharvai** [confluentinc/kafka-connect-storage-cloud#18]
I am receiving the following `NullPointerException`:

```
java.lang.NullPointerException
	at io.confluent.connect.s3.S3SinkTask.close(S3SinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:435)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:147)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

My config is the following:

```json
{
  "connector.class": "io.confluent.connect.s3.S3SinkConnector",
  "s3.region": "us-east-1",
  "partition.duration.ms": "900000",
  "flush.size": "3",
  "schema.compatibility": "NONE",
  "topics": "events_topic",
  "tasks.max": "1",
  "s3.part.size": "5242880",
  "timezone": "UTC",
  "locale": "en",
  "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
  "hive.integration": "false",
  "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
  "schema.generator.class": "io.confluent.connect.storage.hive.schema.TimeBasedSchemaGenerator",
  "name": "EventsS3",
  "storage.class": "io.confluent.connect.s3.storage.S3Storage",
  "s3.bucket.name": "my-bucket",
  "path.format": "'events'/YYYY/MM/DD/HH/"
}
```

Can you please advise how I can correct this error?

Thanks,

**Comment by ewencp** [comment]
@atharvai Based on the code it doesn't seem like that should be possible since we create `TopicPartitionWriters` (which seems to be the source of the `NullPointerException`) for all the assigned partitions and the code that is throwing the exception is just cleaning them up.

Is there any more information in the surrounding log? It might help to know what state the connector was in when it hit this exception.

**Comment by atharvai** [comment]
here's a log: https://gist.github.com/atharvai/960e77f2261832325276fe992fcc7e04

so the actions was I had to restart the connector.

**Comment by atharvai** [comment]
I should mention that this was running from cp-3.1.2 docker image. I see that cp-3.2.0 images were released 3 days ago, so I will test in them too and post any feedback here

**Comment by kkonstantine** [comment]
S3 connector depends on the features introduced by [KIP-89](https://cwiki.apache.org/confluence/display/KAFKA/KIP-89%3A+Allow+sink+connectors+to+decouple+flush+and+offset+commit)

This makes the connector compatible with CP >= 3.2.0 and Kafka >= 0.10.2.0
Thanks for the clarification. We should probably add these compatibility requirements in a more visible place.

**Comment by atharvai** [comment]
Thanks! I guess I jumped the gun on testing it.

**Comment by kkonstantine** [comment]
Np. There's no such thing as too early adoption for us :) 
I'll go ahead and mark this issue as closed.
