### ISSUE TITLE
Best way to skip messages that are not deserializable

### ISSUE THREAD

**Issue by klamouri** [confluentinc/kafka-connect-storage-cloud#182]
Hi,
Every now and them one of the teams in my organization push Avro messages that cannot be deserialized.

It happened on 3 different occasions in the last 5 months. They produce hundreds of billions of records every day of data every day (around 5TB) with those Avro records but when this happens only a few messages are affected (last time 40). In our real-time pipeline, we are able to skip those events but Kafka-Connect Storage-cloud doesn't allow that. Instead, every single task is gonna fail when they are going to try and deserialize those events.

My Question is what can we do to skip those faulty messages?

I'd be happy to contribute if I have at least some pointers on what would be the best way to deal with that

Here is the status of one the connector that fails when it happens

```
{
    "name": "redacted-events",
    "connector": {
        "state": "RUNNING",
        "worker_id": "redacted:8083"
    },
    "tasks": [
        {
            "state": "FAILED",
            "trace": "org.apache.kafka.connect.errors.DataException: TOPIC\n\tat io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:96)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:454)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:287)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 81\nCaused by: java.lang.ArrayIndexOutOfBoundsException\n",
            "id": 18,
            "worker_id": "redacted:8083"
        }
    ],
    "type": "sink"
}

```

**Comment by cricket007** [comment]
I also experience similar issues operating this connector in a large org. 

Typically, we just monitor the failed tasks, and sometimes let the topic retention to it's thing while we periodically attempt to restart the tasks. Obviously, not ideal as there is a window of time where records expire, but at least the connector is not indefinitely down. 

Overall, I believe [KAFKA-6738](https://issues.apache.org/jira/browse/KAFKA-6738) addresses error handling

**Comment by klamouri** [comment]
Yes, and it has been released today. I'll use this
