### ISSUE TITLE
Add support for Avro compression.

### ISSUE THREAD

**Issue by westerly** [confluentinc/kafka-connect-storage-cloud#21]
Hi guys it would be nice to be able to configure the s3 connector to compress Avro data when using the AvroRecordWriterProvider. The different compression codecs supported by Avro are snappy and deflate.

**Comment by kkonstantine** [comment]
This is worth checking out once the pending changes are merged. In the meantime, please feel free to contribute a patch if you feel strong about this feature. (I've noticed a similar request has been made for the HDFS connector and I now see you're working on a PR there: https://github.com/confluentinc/kafka-connect-hdfs/issues/174)

**Comment by BDeus** [comment]
I think this is done since https://github.com/confluentinc/kafka-connect-storage-cloud/commit/a3417533cacb24a1598de457ddcd28585b287fa4
This issue can be closed

**Comment by kkonstantine** [comment]
Indeed. The feature has been merged. Closing.
