### ISSUE TITLE
Connector status endpoint HTTP response codes

### ISSUE THREAD

**Issue by gitrc** [confluentinc/kafka-connect-storage-cloud#215]
It appears that the HTTP response code for the status endpoint is always 200/OK.  It would be extremely helpful if the response code was NOT 200/OK if there are FAILED connector states or task states.  Having to parse the response body JSON in order to determine actual health adds unnecessary burden on the upstream client doing the health check.

Based on the existing documentation you can see that even though there is a FAILED worker task the HTTP response code is 200/OK (https://docs.confluent.io/current/connect/references/restapi.html#get--connectors-(string-name)-status)

We run these connectors in Docker containers and have resorted to Docker health checks (calling a simple script to parse the JSON status response body) but would much prefer to leverage the HTTP response code as that is the lowest common denominator supported by most proxies/load balancers etc.

**Comment by cricket007** [comment]
@gitrc This should probably be a [JIRA ticket for the base Kafka project](https://issues.apache.org/jira/projects/KAFKA/issues), not a specific Connect plugin

**Comment by gitrc** [comment]
@cricket007 will do, thanks.

**Comment by adiaviv05** [comment]
I also ran across this problem. I decided to resolve it with bash script which parse the response '/health' JSON body request and determine if one of the connectors 'FAILED'.

The 'health_check.sh' script :

_#!/bin/bash
DATA=$(curl -s uint-kafka-connect:8083/connectors)
IFS='[,]' read -ra CONNECTORS <<< ${DATA}
for connector in ${CONNECTORS[*]}
do
    echo "$connector"
    CONNECTOR=$(echo $connector | tr -d '"')
    STATUS=$(curl -s uint-kafka-connect:8083/connectors/$CONNECTOR/status)
    if [[ $STATUS == *"FAILED"* ]]; then
        exit 1
    fi
done_
 

Activate the script from .yaml :

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: uint-kafka-connect
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: uint-kafka-connect
        image: quay.io/wework/uint-kafka-connect
        imagePullPolicy: Always
        securityContext:
          privileged: true
        **livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - /health_check.sh**
          initialDelaySeconds: 30
          periodSeconds: 30

Hope you will find it useful.

**Comment by cricket007** [comment]
I don't know k8s, but if liveliness checks will restart failed pods, this is cause endless rebalancing of the connect consumer group for all connectors in the cluster, not just the failed one. 

Something to keep in mind
