### ISSUE TITLE
Add support to sync data from Kafka to S3 as it is. 

### ISSUE THREAD

**Issue by westerly** [confluentinc/kafka-connect-storage-cloud#22]
Hi guys,

From what I understand it is not possible to sync schemaless data from Kafka to s3 right now. Would it be possible to support syncing data as it is from Kafka to s3 if the Hive integration is not activated? 

We have an use case in my company where we want to sync plain Strings to S3 so this feature would be awesome to have. Also it would be cool to be able to compress the data synced with Snappy or gzip.

**Comment by kkonstantine** [comment]
Exporting JSON records without schema is already supported with the S3 connector. Exporting binary records "as is" should also be straightforward now that the BinaryArrayConverter has become part of the public set of converters in Kafka (related PR: https://github.com/apache/kafka/pull/2599 and KIP: [128](https://cwiki.apache.org/confluence/display/KAFKA/KIP-128%3A+Add+ByteArrayConverter+for+Kafka+Connect)). 

Once the time-based partitioners are merged, we'll add more specific examples in the quickstart guide to highlight how exporting without schemas works.

**Comment by jklukas** [comment]
> We have an use case in my company where we want to sync plain Strings to S3 so this feature would be awesome to have. Also it would be cool to be able to compress the data synced with Snappy or gzip.

I second this. My team currently maintains our own service for batching up Kafka topics full of JSON-formatted strings and archiving them as newline-delimited gzipped objects in S3 (which Redshift is then able to ingest directly).

I'd love to see an configuration option to compress objects before putting to S3.

**Comment by jklukas** [comment]
> Once the time-based partitioners are merged, we'll add more specific examples in the quickstart guide to highlight how exporting without schemas works.

This would be a great addition.

**Comment by jklukas** [comment]
Time-based partitioners are merged now. I'd still love to see some documentation about exporting without schemas.

**Comment by jklukas** [comment]
See potential implementations of compression and binary data in #83 and #85

**Comment by jklukas** [comment]
ByteArrayFormat support was merged in #85

**Comment by kkonstantine** [comment]
The feature has been added as noted above. Closing

**Comment by doriwal** [comment]
Hi

I am trying to use gzip but its not working , I am reading json events from kafka
confluent version is 4.0.0

{
"connector.class": "io.confluent.connect.s3.S3SinkConnector",
"s3.region": "us-east-1",
"partition.duration.ms": "10",
"flush.size": "3000",
"schema.compatibility": "NONE",
"timezone": "UTC",
"tasks.max": "6",
"topics": "MY_EVENT_JSON",
"s3.part.size": "5242880",
"locale": "en",
"key.converter.schemas.enable": "false",
"s3.compression.type": "gzip",
"format.class": "io.confluent.connect.s3.format.json.JsonFormat",
"partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
"name": "MY_EVENT_JSON",
"schema.generator.class": "io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator",
"value.converter.schemas.enable": "false",
"value.converter": "org.apache.kafka.connect.json.JsonConverter",
"storage.class": "io.confluent.connect.s3.storage.S3Storage",
"s3.bucket.name": "s3-testing",
"path.format": "YYYY-mm-DD/HH",
"timestamp.extractor": "RecordField",
"key.converter": "org.apache.kafka.connect.storage.StringConverter",
"timestamp.field": "eventTimestamp"
}

**Comment by doriwal** [comment]
If it help I see this error in connect logs 


java.lang.LinkageError: loader (instance of  org/apache/kafka/connect/runtime/isolation/PluginClassLoader): attempted  duplicate class definition for name: "org/apache/xerces/impl/dv/dtd/DTDDVFactoryImpl"
