### ISSUE TITLE
Add support for ingestion time based partitioner to s3 connector. 

### ISSUE THREAD

**Issue by westerly** [confluentinc/kafka-connect-storage-cloud#23]
Hi all,

Could we add time based partitioning support based on Kafka ingestion time of the messages? This can be done easily by extending the TimeBasedPartitioner class and grabbing the timestamp from the sink record in the encodePartition method. However I am not too sure if this would guarantee exactly once delivery like the default partitioner does. 

I would be glad to help if you can direct me on how to achieve this.

**Comment by kkonstantine** [comment]
Hi @westerly,
thanks for mentioning this feature and for volunteering. Let me note that this is already underway in the following PRs: 

https://github.com/confluentinc/kafka-connect-storage-common/pull/18
and https://github.com/confluentinc/kafka-connect-storage-cloud/pull/19

This is an enhancement aiming to make the current time-based partitioning more configurable and independent of Wall-clock time (giving it exactly-once semantics). 

Should be merged to master soon.

**Comment by westerly** [comment]
Awesome thanks for these precisions @kkonstantine.

**Comment by steveratay** [comment]
Is there a target release for these improvements? Thanks!

**Comment by kkonstantine** [comment]
Time-based partitioning has been enhanced in `v3.2.2` and will also appear in the upcoming `3.3.0` (represented by the `3.3.x` branch currently). Of course the changes are present in the `master` branch too. 

Therefore, I'm closing the ticket.
