### ISSUE TITLE
Filtering messages out using a SMT leads to very high consumer lag in S3 sink

### ISSUE THREAD

**Issue by zzbennett** [confluentinc/kafka-connect-storage-cloud#232]
I have a SMT that can filter arbitrary messages out of a topic. It returns `null` for messages that should be filtered, and the kafka connect framework will then drop the message. For all my sinks and sources this is working as expected, except in the S3 sink. When null records come through, the S3 sink never commits the offsets for the records that were filtered out. This can lead to consumers having a very large offset lag. 

I poked around the code and noticed the S3 sink has some custom logic in the `preCommit` method. I gather this is so that we don't commit offsets to kafka for data that has not yet been flushed to S3, which makes sense.

I know there are a lot of ways to go about filtering messages, but this approach has been working really well for us and gives us a lot of flexibility. However, this issue with the S3 sinks is starting to cause us some production issues, as consumers with very high lag will start over and re-consume a lot of data whenever there is a re-balance in kafka connect.

I made a fix for it that does not seem to break any existing functionality, but fixes our issue. If the fix looks okay and you'd be willing to merge it, I will fix it up and add tests.

Fix is here: https://github.com/zzbennett/kafka-connect-storage-cloud/commit/ba71fe01dc902fe7d42156736d225d529c0d178f

**Comment by zzbennett** [comment]
Created a PR here https://github.com/confluentinc/kafka-connect-storage-cloud/pull/234

**Comment by zzbennett** [comment]
We ended up migrating our topic topology to avoid this problem, so will close this issue

**Comment by arnitolog** [comment]
@zzbennett can I ask you to share your solution to filter out the message. I'm looking for the same functionality and it appears that it is only possible with custom Transformation. Will be glad to be wrong :)
