### ISSUE TITLE
Could not find artifact io.confluent:licenses:jar:3.2.0 in central

### ISSUE THREAD

**Issue by zzbennett** [confluentinc/kafka-connect-storage-cloud#24]
I just cloned the `kafka-connect-storage-cloud` project. After checking out the v3.2.0 tag, I attempted to do a `mvn install`. This produced the following error:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] kafka-connect-storage-cloud ........................ SUCCESS [  0.179 s]
[INFO] kafka-connect-s3 ................................... FAILURE [01:21 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:22 min
[INFO] Finished at: 2017-03-23T18:45:34+00:00
[INFO] Final Memory: 55M/563M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (create-licenses) on project kafka-connect-s3: Execution create-licenses of goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java failed: Plugin org.codehaus.mojo:exec-maven-plugin:1.2.1 or one of its dependencies could not be resolved: Could not find artifact io.confluent:licenses:jar:3.2.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

To get past it, I just commented out the `licenses-package` profile in the kafka-connect-s3 pom.xml.

At any rate, I figured I'd report the issue since it looks like an issue with confluent's jars.

**Comment by ewencp** [comment]
@zzbennett Yeah, that's our bad. The repo for that particular jar isn't currently public.

**Comment by memelet** [comment]
Is the jar going to made public?

**Comment by ewencp** [comment]
@memelet This was fixed in https://github.com/confluentinc/kafka-connect-storage-cloud/pull/28. You can simply modify the pom to disable the profile that uses this dependency by default so it won't try to download and use the jar (it won't have any impact on the artifacts that are built).
