### ISSUE TITLE
Graceful handling of wrong message format

### ISSUE THREAD

**Issue by krangerich** [confluentinc/kafka-connect-storage-cloud#259]
When I create a S3SinkConnector with format.class: io.confluent.connect.s3.format.JsonFormat and the (default?) value.converter org.apache.kafka.connect.json.JsonConverter, everything works fine and the connector correctly writes JSON into S3 objects.

When for whatever reason a malformed JSON object is in the kafka topic, the S3 connector crashes with a serialization error. Of course, technically thats correct, because the content is supposed to be JSON.
But in that case, I'm not able to recover. The broken message stays in the topic and keeps crashing the S3 connector. 

There should be a configuration option how to handle broken messages, for example to just skip/ignore them.

**Comment by tarpdalton** [comment]
`"errors.tolerance" : "all",`

https://www.confluent.io/blog/kafka-connect-deep-dive-error-handling-dead-letter-queues

**Comment by krangerich** [comment]
Thats it, thanks a lot!
