### ISSUE TITLE
AWS Credentials profile per connector

### ISSUE THREAD

**Issue by antonioiorfino** [confluentinc/kafka-connect-storage-cloud#265]
Hi,

I'm using the Kafka Connect to send data from topics to S3 buckets. The connectors works fine and I have used the the `com.amazonaws.auth.profile.ProfileCredentialsProvider` as 
`s3.credentials.provider.class`.

The connector works using the credentials defined in `/home/user/.aws/credentials` but only with the default profile.

Inside the documentation I do not found any instructions how to use a specific profile credentials for a connector.
Do you think could be possible in a future release to have this feature or the idea is to have always the same credentials for all bucket used?

**Comment by kkonstantine** [comment]
Defining credentials per connector is now addressed with: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/305
