### ISSUE TITLE
Failure to commit multipartupload results in apparent data loss

### ISSUE THREAD

**Issue by Thoymas** [confluentinc/kafka-connect-storage-cloud#269]
Hello,

We're running confluent-kafka-connect-s3.noarch version 5.1.2-1.
We have seen that when an attempt to commit a MultipartUpload fails, due to for example an S3 throttling error, this causes the task to just continue while leaving the S3 object that corresponds to the MultipartUpload invisible, since the commit is never done.
This seems to happen only when files are rotated on time.

Having the connector silently (except for log messages) continue after a failure like this can cause at least apparent data loss which reduces the confidence in the application. Perhaps this is by design, if so I would be glad to hear the rationale behind the decision. In my view, it would be better to fail the task completely in this scenario.

To walk through the flow as I understand it.
* An exception is thrown by the AWS lib and is caught here: https://github.com/confluentinc/kafka-connect-storage-cloud/blob/5.1.2-post/kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java#L156
* This logs and rethrows the exception but in the finally clause, the buffer is closed and the stream itself is also marked as closed.
The rethrown exception is then caught here: https://github.com/confluentinc/kafka-connect-storage-cloud/blob/5.1.2-post/kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java#L295 which then schedules a retry attempt.
* The retry attempt when it runs then reaches the commit method again but since the stream is closed, just silently returns: https://github.com/confluentinc/kafka-connect-storage-cloud/blob/5.1.2-post/kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java#L146

In our logs we see these sequence of messages when it has happened:
* 2019-08-25 05:00:35,805 ERROR io.confluent.connect.s3.storage.S3OutputStream:157 - Multipart upload failed to complete for bucket 'bucketA' key 'some-prefix/objectA'
* 2019-08-25 05:30:34,605 WARN io.confluent.connect.s3.storage.S3OutputStream:141 - Tried to commit data for bucket 'bucketA' key 'some-prefix/objectA' on a closed stream. Ignoring. 
* 2019-08-25 05:30:34,605 DEBUG io.confluent.connect.s3.TopicPartitionWriter:484 - Committed some-prefix/objectA for topicA-2

We're not confident enough with this codebase to suggest a solution but would be very happy if someone has any ideas. 

Best Regards
Thomas

**Comment by kkonstantine** [comment]
A fix has been merged in all the release branches. 
According to the fix the connector now will retry correctly failure that happen during the commit/close phase of the multipart upload. Currently the task will fail if a failure happens at earlier during the upload. 

Thanks for reporting. Let us know if this fixes the issue. The fix will appear in all the upcoming bugfix and regular releases.
