### ISSUE TITLE
rotate.interval.ms configuration not taken in account in the s3 connector 

### ISSUE THREAD

**Issue by westerly** [confluentinc/kafka-connect-storage-cloud#27]
Hi all,

I have noticed the property rotate.interval.ms doesn't seem to be taken in account in my s3 connector tasks. I have noticed this configuration among rotate.schedule.interval.ms and shutdown.timeout.ms are black listed in the S3SinkConnectorConfig class. 
What is the reason and would it be possible to use these configuration properties in the s3 connector? 

It is really important for us to be able to rotate files based on time interval. Depending of our traffic, our data ingestion rate can be low and the connector doesn't write enough messages sometimes to trigger a file upload.

**Comment by wdaehn** [comment]
+1
Of course you have topics with high frequency data ingestion but there are other topics with a lower volume always. Say I get millions of device messages per second but one topic contains the device location - which gets a handful of changes per day. 
Hence the device location topic would be flushed once every year - when the flush size is reached? Won't work.

**Comment by Azuaron** [comment]
This bit of code's in S3SinkConnectorConfig:

```java
public static ConfigDef getConfig() {
    Map<String, ConfigDef.ConfigKey> everything = new HashMap<>(CONFIG_DEF.configKeys());
    everything.putAll(StorageCommonConfig.getConfig().configKeys());
    everything.putAll(PartitionerConfig.getConfig().configKeys());

    Set<String> blacklist = new HashSet<>();
    blacklist.add(StorageSinkConnectorConfig.ROTATE_INTERVAL_MS_CONFIG);
    blacklist.add(StorageSinkConnectorConfig.ROTATE_SCHEDULE_INTERVAL_MS_CONFIG);
    blacklist.add(StorageSinkConnectorConfig.SHUTDOWN_TIMEOUT_CONFIG);

    ConfigDef visible = new ConfigDef();
    for (ConfigDef.ConfigKey key : everything.values()) {
      if(!blacklist.contains(key.name)) {
        visible.define(key);
      }
    }
    return visible;
  }
```

**Comment by kkonstantine** [comment]
The property is now taken into account in the most recent versions of the connector. Thus, I'm closing this ticket.
