### ISSUE TITLE
When can we expect Kafka Connect S3 on confluent hub to include the parquet support? 

### ISSUE THREAD

**Issue by HumairAK** [confluentinc/kafka-connect-storage-cloud#290]
Latest version of Kafka Connect S3 does not have the parquet format support that was [merged not too long ago](https://github.com/confluentinc/kafka-connect-storage-cloud/pull/241). When can we expect this update to reflect upon the version available on confluent hub as we are highly anticipating it? I've attempted to manually install the connector plugin with the parquet support, but keep encountering issues, it would certainly be easier if I could just use the confluent hub cli to install it instead. Thanks.

**Comment by kkonstantine** [comment]
The S3 sink connector still ships (and therefore gets released) with the rest of the Confluent Platform. So, a new version is uploaded to confluent hub when the actual Confluent Platform is released. 

This might change in the future and then all connectors will have independent release cadence. At the moment, the plan is for Parquet support in S3 connector to arrive with the upcoming 5.4 release. 

If you don't want to wait, to install from source, given that you need to build a snapshot version, try to checkout and install the prerequisite packages first, as described here: 
https://github.com/confluentinc/kafka-connect-storage-common/wiki/FAQ
and then run `mvn clean package` in this repo. 

At the end of this step, a `zip` archive will be generated which you may install with `confluent-hub-client` by pointing to this archive in your local filesystem.

**Comment by kkonstantine** [comment]
Closing since this question was answered. Stay tuned for the upcoming 5.4.0 release!

**Comment by pualien** [comment]
hi @kkonstantine any update on when it'll be released?
