### ISSUE TITLE
FAQ Problem

### ISSUE THREAD

**Issue by zuquan-song** [confluentinc/kafka-connect-storage-cloud#295]
Hi, about the wiki [the kafka-connect-storage-common FAQ](https://github.com/confluentinc/kafka-connect-storage-common/wiki/FAQ), I think it miss an additional dependency, which is kafka-connect-storage-common. 
After I add:
`git clone git@github.com:confluentinc/kafka-connect-storage-common.git`
`mvn install`
Everything goes well.

**Comment by kkonstantine** [comment]
@zuquan-song the aforementioned repo it's also where the FAQ resides. 
But you are right, storage common needs also to be installed with `mvn install` in order to be available to other storage sink connectors such as S3 or HDFS connectors. 

I extended the FAQ to add this command as well. Cheers!

**Comment by cricket007** [comment]
Hi @kkonstantine , would you link the FAQ into the README, please & thanks?
