### ISSUE TITLE
S3 Sink Connector - Possible to remove topic name from S3 paths?

### ISSUE THREAD

**Issue by dseravalli** [confluentinc/kafka-connect-storage-cloud#321]
Hi,

How would I set up the connector so that the Kafka topic names are not included in the output S3 paths?

I'm using the `TimeBasedPartitioner` and I'd like to have a fixed name in the path instead of the topic name. So this:

`fixed_name/<encodedPartition>/<topic>+<kafkaPartition>+<startOffset>.<format>`

Instead of the default:

`topics/<topic>/<encodedPartition>/<topic>+<kafkaPartition>+<startOffset>.<format>`

**Comment by dseravalli** [comment]
This is possible if one writes a custom partitioner class.

**Comment by hashhar** [comment]
@dseravalli Can you please elaborate?

From https://docs.confluent.io/current/connect/kafka-connect-s3/index.html#s3-object-names:

> In general, the names of the S3 object uploaded by the S3 connector follow this format:
> 
> <prefix>/<topic>/<encodedPartition>/<topic>+<kafkaPartition>+<startOffset>.<format>
> 
> Copy
> 
> where:
> 
>     <prefix> is specified with the connector’s topics.dir configuration property, which defaults to the literal value topics and helps create uniquely name S3 objects that don’t clash with existing S3 objects in the same bucket.
>     **<topic> corresponds to the name of the Kafka topic from which the records in this S3 object were read.**
>     **<encodedPartition> is generated by the S3 connector’s partitioner (see Partitioning Records into S3 Objects).**
>     <kafkaPartition> is the Kafka partition number from which the records in this S3 object were read.
>     <startOffset> is the Kafka offset of the first record written to this S3 object.
>     <format> is the extension identifing the format in which the records are serialized in this S3 object.

I can see that only the `encodedPartition` portion is decided by the partitioner class. How were you able to get this to work?

**Comment by hashhar** [comment]
I figured it out. Adding a sample here for future readers.
This might not be obvious since if you look into the TimeBasedPartitioner class you might not find any method that generates the path, it's all done in the super-class DefaultPartitioner. So here we are overriding that method.

```java
/**
 * A {@link io.confluent.connect.storage.partitioner.Partitioner} implementation that extends the
 * {@link TimeBasedPartitioner} to create paths without using the topic name as first component of
 * object name.
 *
 * @param <T> the type representing the field schemas
 */
public class CustomTimeBasedPartitioner<T> extends TimeBasedPartitioner<T> {
  @Override
  public String generatePartitionedPath(String topic, String encodedPartition) {
    // we don't want to use topic name so we ignore it
    return encodedPartition;
  }
}
```
