### ISSUE TITLE
java.lang.NoSuchMethodError - Can't find AWS S3 Method

### ISSUE THREAD

**Issue by robot-rk** [confluentinc/kafka-connect-storage-cloud#36]
Did a brand new install on Kafka Connect and I'm seeing this error:

ERROR:

connect-distributed: Caused by: java.lang.NoSuchMethodError: com.amazonaws.services.s3.AmazonS3ClientBuilder.withAccelerateModeEnabled(Ljava/lang/Boolean;)Lcom/amazonaws/services/s3/AmazonS3Builder;

I see the following JARS:
/usr/share/java/kafka-connect-s3/aws-java-sdk-core-1.11.86.jar
/usr/share/java/kafka-connect-s3/aws-java-sdk-kms-1.11.86.jar
/usr/share/java/kafka-connect-s3/aws-java-sdk-s3-1.11.86.jar

Connector Config:
'{
    "name": "s3-sink",
    "config": {
        "connector.class": "io.confluent.connect.s3.S3SinkConnector",
        "tasks.max": "4",
        "type.name": "kafka-connect",
        "topics": "rk-test",
        "flush.size": "3",
        "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
        "s3.bucket.name": "kafka-sink-test",
        "s3.region": "us-west-1",
        "storage.class": "io.confluent.connect.s3.storage.S3Storage",
        "schema.generator.class": "io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator",
        "partitioner.class": "io.confluent.connect.storage.partitioner.DefaultPartitioner",
	"s3.wan.mode":"false"
    }
}'

**Comment by kkonstantine** [comment]
This method is available in recent versions of the AWS S3 java sdk ([javadoc](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Builder.html#withAccelerateModeEnabled-java.lang.Boolean-)). 

The error you are seeing probably means that an older version of the aws sdk is somehow introduced earlier in your classpath (probably by as a dependency). Try adding the dependencies of the S3 connector first (earlier in the CLASSPATH).

**Comment by robot-rk** [comment]
Hey @kkonstantine 

Thanks for the help. I found the conflicting Jar and removed it from Classpath. S3 Connector is working now

**Comment by kkonstantine** [comment]
Glad you sorted this out! I'm closing this issue.
