### ISSUE TITLE
Scheduled rotation config enabled on DST switch day produces file per kafka record

### ISSUE THREAD

**Issue by mvitaly** [confluentinc/kafka-connect-storage-cloud#375]
When scheduled rotation is enabled (`rotate.schedule.interval.ms` config value is positive), on the day of the DST changes (25 hour day), during the last hour of the day kafka connect s3 sink would be rotating files after every record, producing a lot of tiny files.

**Comment by mvitaly** [comment]
have an MR to fix it, will submit shortly

**Comment by kazzakee** [comment]
Has this issue been tested and considered fixed with the above changes? We are experiencing same issues in our clusters and wanted to confirm if using new build with these changes will fix those...

**Comment by mvitaly** [comment]
Oh right, this should be closed now that the PR is merged and new versions were released.

We are running the latest releases and we don't see the original problem anymore.
