### ISSUE TITLE
How to skip records

### ISSUE THREAD

**Issue by rooom13** [confluentinc/kafka-connect-storage-cloud#417]
Is there a way to configure a connector to skip some events based on a field's value?

I can imagine there should be a way of skipping records e.g: Don't store the event on s3 if fieldA is 'testSkip'

`record.skipIf="fieldA=='testSkip'"`

But could not find anything about this in the docs

**Comment by OneCricketeer** [comment]
There's a Drop transform, but has limited usage

https://docs.confluent.io/platform/current/connect/transforms/drop.html

The recommendation is to filter the records beforehand using KSQL or Kafka Streams
