### ISSUE TITLE
Support rotating by time to any partitioner

### ISSUE THREAD

**Issue by daehokimm** [confluentinc/kafka-connect-storage-cloud#434]
Hi All

Now, Rotate by time settings (like rotate.interval.ms) apply when partitioner class is TimebasedPartitioner. So FieldPartitioner and others can not rotate by time. but other partitioners need to rotate by time. So I suggests to remove the dependency between rotate settings and TimebasedPartitioner, and apply rotate settings as connector config.

**Comment by OneCricketeer** [comment]
Partitioners are implemented in a different repo, so not sure this issue belongs here

FieldAndTime partitioner was implemented here - https://github.com/confluentinc/kafka-connect-storage-common/pull/73
