### ISSUE TITLE
Support for topic wildcard?

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/kafka-connect-storage-cloud#46]
Does this connector have support for topic wildcard, i.e.

```
topics=*.avro
```
or
```
topics=avro.*
```

?

**Comment by Azuaron** [comment]
As I understand it, this is controlled at the Kafka Connect core level, not the plugin level. https://issues.apache.org/jira/browse/KAFKA-3073

**Comment by kkonstantine** [comment]
Indeed. Marking as `enhancement` and keeping open to track when such a feature will be available in through the framework.

**Comment by kkonstantine** [comment]
This functionality has been merged in the Connect framework.

**Comment by kmillanr** [comment]
> Does this connector have support for topic wildcard, i.e.
> 
> ```
> topics=*.avro
> ```
> 
> or
> 
> ```
> topics=avro.*
> ```
> 
> ?

Dear Simpletesh, was this issue ever solved? I cannot find a single place where (without the use of java) there is a clear straightforward command or properties change in the json config to do this, or is doing it through java the only path?

**Comment by dalassi1** [comment]
@kmillanr  `TOPICS_REGEX_CONFIG = "topics.regex"` ?

**Comment by kmillanr** [comment]
> @kmillanr `TOPICS_REGEX_CONFIG = "topics.regex"` ?

Dear Dalasi, thank you for the response: Is there a way to do it in the terminal  for the BigQuery Sink connector (I don't know java yet)? I have been reading about it and as far as I've seen the connector does not have a topics.regex property....
