### ISSUE TITLE
[Feature] flush.ms

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/kafka-connect-storage-cloud#47]
Unsure how hard to implement, but it would be great to commit based on the first attained of `flush.ms` & `flush.size`. That would allow data to be frequently committed no matter what and provide an upper bound to how late data can be in S3.

**Comment by steveratay** [comment]
This would be a great feature. I'm looking at using time-based partitioning and would like to ensure that when the time interval rolls over to the next minute, hour, etc. all messages are flushed to the previous interval's S3 object in a reasonable amount of time (i.e. flush.ms).  Based on what I have read and observed, until flush.size messages are received, the messages will not be flushed even when the messages are in a time-based partition to which records no longer can be written.

**Comment by BDeus** [comment]
It is not already possible with `rotate.schedule.interval.ms` ?
I agree that there is no documentation about this parameter. By reading the code, it sounds like what you want to do.

**Comment by Azuaron** [comment]
Unless something has changed very recently, both those properties are blacklisted.

**Comment by BDeus** [comment]
Can't find that these properties are deprecated.
In the next pull of an implementation of exactly once time based partitioning (https://github.com/confluentinc/kafka-connect-storage-cloud/pull/19), these properties continue to be used.

**Comment by Azuaron** [comment]
Added to [the blacklist](https://github.com/confluentinc/kafka-connect-storage-cloud/blob/master/kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkConnectorConfig.java) (line 311).
`
    Set<String> blacklist = new HashSet<>();
    blacklist.add(StorageSinkConnectorConfig.ROTATE_INTERVAL_MS_CONFIG);
    blacklist.add(StorageSinkConnectorConfig.ROTATE_SCHEDULE_INTERVAL_MS_CONFIG);
    blacklist.add(StorageSinkConnectorConfig.SHUTDOWN_TIMEOUT_CONFIG);
`

**Comment by BDeus** [comment]
Ok see it. 
But i'm wonder if it's really wanted since there are some implementation with this params in the next version.
@ewencp @kkonstantine  do you know if the blacklist of rotate interval is still blacklist ?
Thanks for answer

**Comment by kkonstantine** [comment]
Not removing `ROTATE[INTERVA,SCHEDULE_INTERAVAL]_MS_CONFIG` from the blacklist was an oversight. (I'm equally surprised since I remember (~removing~) intending to remove those). After the time-based EOS PR was merged (https://github.com/confluentinc/kafka-connect-storage-cloud/pull/19) these two configs have been re-enabled. 

They can be used right away since the blacklist is used during config validation. But I'll issue a PR shortly.

**Comment by kkonstantine** [comment]
The properties above have been enabled in the code and have been removed from the blacklist. Thus, I'm closing this ticket.
