### ISSUE TITLE
Add option to support synchronous offset commit in Kafka Connect Sink

### ISSUE THREAD

**Issue by adasari** [confluentinc/kafka-connect-storage-cloud#484]
Exactly once in s3 connector with scheduled rotation and field partitioner can be achieved with consumer offset sync' commit after message batch flushed to sink successfully. This is not idempotent though. 

Currently, WorkerSinkTask committing the consumer offsets asynchronously and at regular intervals of WorkerConfig.OFFSET_COMMIT_INTERVAL_MS_CONFIG 

https://github.com/apache/kafka/blob/371f14c3c12d2e341ac96bd52393b43a10acfa84/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L203

https://github.com/apache/kafka/blob/371f14c3c12d2e341ac96bd52393b43a10acfa84/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L196

https://github.com/apache/kafka/blob/371f14c3c12d2e341ac96bd52393b43a10acfa84/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L354

Add config to allow user to select synchronous commit over WorkerConfig.OFFSET_COMMIT_INTERVAL_MS_CONFIG

**Comment by raphaelauv** [comment]
The connector manage itself the offset commit

https://github.com/confluentinc/kafka-connect-storage-cloud/blob/135871d600317ff207543f326919a17211a8b1fc/kafka-connect-s3/src/main/java/io/confluent/connect/s3/S3SinkTask.java#L269

![evolution lag consumer group (1)](https://user-images.githubusercontent.com/10202690/152808216-e77c81ff-2cf7-45c9-bb31-a227ef40f566.png)

**Comment by adasari** [comment]
@raphaelauv you are right. i will create ticket in kafka repo. thanks.
