### ISSUE TITLE
Allow custom partitioners to have their own configs

### ISSUE THREAD

**Issue by zzbennett** [confluentinc/kafka-connect-storage-cloud#49]
I've written a custom partitioner that requires a few configs (basically db name & table name). The S3SinkTask does not pass down all the configs it receives upon instantiation to the custom partitioner however. In S3SinkConnectorConfig, only a specific set of configs are exposed, namely, those present in StorageCommonConfig, HiveConfig and PartitionerConfig.

What I need basically is for all of the initial set of configs to get passed within the map that the custom partitioner is configured with. Ideally, instead of the S3SinkTask using the config.plainValues() method to pass the configs to the partitioner, it would use the config.originals() method.

I would be willing to submit this patch, unless there is some reasoning for not making this change. If so, some kind of other work around would be awesome and I'm open to suggestions.

**Comment by zzbennett** [comment]
I went ahead and created the patch anyways since it was a small change. I still use the config.plainValues() method, but pass in any extra configs from the config.originals() method.

Please take a look and let me know if there's anything I should change.

**Comment by kkonstantine** [comment]
Resolved by: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/51

Thanks again for the PR!
