### ISSUE TITLE
What if you dont't want any partitioner?

### ISSUE THREAD

**Issue by ismail261** [confluentinc/kafka-connect-storage-cloud#55]
Hi,

I would like to write data to s3 by just specifying bucket name and path but would not like to use partitioner class. It uses default partitioner by default which appends partition=0 in the s3 key.

Is there any way to avoid that?

Thanks,
Ismail

**Comment by kkonstantine** [comment]
Hi @ismail261 
from what you describe, I believe it would make sense for you to extend the [Partitioner](https://github.com/confluentinc/kafka-connect-storage-common/blob/master/partitioner/src/main/java/io/confluent/connect/storage/partitioner/Partitioner.java) interface and implement your own logic to your partitioner, which sounds you expect to be pretty simple. You would then pass this partitioner class in the configuration properties of the S3 connector. 

Hope this helps.

**Comment by ismail261** [comment]
Thanks @kkonstantine . i just wanted to confirm if i am not missing any configs that has been already provided.

Also would you know why the key name that gets constructed for s3 storage has topic name in it? Would be really good if you can choose your own key names.

**Comment by kkonstantine** [comment]
Encoding the topic, the partition and the starting offset to the object key makes sense in order to achieve deterministic export of records and potentially exactly-once semantics.  

Should we close this ticket at this point?

**Comment by kkonstantine** [comment]
I'm closing this one since there's another ticket addressing the naming issue here: https://github.com/confluentinc/kafka-connect-storage-cloud/issues/52
