### ISSUE TITLE
Setting s3.ssea.name to AES256 has no effect, no encryption is applied for JSON files

### ISSUE THREAD

**Issue by nagys007** [confluentinc/kafka-connect-storage-cloud#57]
But the parameter s3.ssea.name is being passed to s3 connector. How do I know? I tried AES-256 as value for this parameter and I got
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The encryption method specified is not supported (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: ...
Anybody who has successfully used this parameter?

**Comment by nagys007** [comment]
My mistake, got confused by the AWS S3 WebUI. It shows "Encryption" as "-" on the object. After switching to S3 browser. I could confirm under properties, that it is on. Also, on the detail page for object, the server-side encryption is shown as "AES-256".

**Comment by darrenhaken** [comment]
@nagys007 did you ever get this working? Can you provide the key/value pair you used to have encryption working?

**Comment by nagys007** [comment]
Hi Darren, I'm not in the project anymore, but yes, we managed to get it working. No explicit key/value pair was used. The standard server side encryption took place.

**Comment by rawipfel** [comment]
Hi, just to clarify the expected behavior, if one only sets ```s3.ssea.name=AES256``` and leaves ```s3.sse.customer.key``` and ```s3.sse.kms.key.id``` unset, then the S3 connector will encrypt via  SSE-S3 . The latest code suggests that here: https://github.com/confluentinc/kafka-connect-storage-cloud/blob/master/kafka-connect-s3/src/main/java/io/confluent/connect/s3/storage/S3OutputStream.java#L183
