### ISSUE TITLE
Implement AAD authentication support for Azure Blob connectors (sink/source)

### ISSUE THREAD

**Issue by yuhusolutions** [confluentinc/kafka-connect-storage-cloud#608]
Hi, this is an enhancement request regarding azure-blob-storage sink and source connectors.
https://docs.confluent.io/kafka-connectors/azure-blob-storage-sink/current/configuration_options.html
https://docs.confluent.io/kafka-connectors/azure-blob-storage-source/current/configuration_options.html

The existing implementation of the connector (2.4.4) does not allow to use Azure AD (AAD) authentication, forcing the usage of the storage account shared key. 
AAD enables to use named and distinct identities to read and write to the storage account container. 

The current behavior (2.4.4) does not align with Microsoft recommendations:
> Microsoft recommends that you disallow Shared Key authorization for your storage account. When Shared Key authorization is disallowed, clients must use Azure AD or a user delegation SAS to authorize requests for data in that storage account. For more information, see [Prevent Shared Key authorization for an Azure Storage account](https://learn.microsoft.com/en-us/azure/storage/common/shared-key-authorization-prevent).
> 
> https://docs.microsoft.com/en-us/azure/storage/common/authorize-data-access?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json#understand-authorization-for-data-operations

Other components for Azure provided by Confluent support AAD authentication. Such as [azure-data-lake-gen1](https://docs.confluent.io/kafka-connectors/azure-data-lake-gen1-sink/current/configuration_options.html), [azure-data-lake-gen2](https://docs.confluent.io/kafka-connectors/azure-data-lake-gen2-sink/current/configuration_options.html) .

Would you consider adding AAD support for azure-blob-storage connect component?

Thank you.

Additional information:
Note that OSS framework (apache camel, apache kafka-connect) supports AAD since 3.18.  https://camel.apache.org/camel-kafka-connector/3.18.x/reference/connectors/camel-azure-storage-blob-sink-kafka-sink-connector.html
"azure-data-lake-gen1" will be retired in favor of Gen2 in the next year: https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/

**Comment by OneCricketeer** [comment]
Hi. You can see from the README, this is the S3 sink connector.

**Comment by yuhusolutions** [comment]
Ooops. Wrong project.
