### ISSUE TITLE
Export data with json format to s3

### ISSUE THREAD

**Issue by chuyouxin** [confluentinc/kafka-connect-storage-cloud#89]
Why the data is the json string when export data to s3 not json?
My config:
name=s3-sink
connector.class=io.confluent.connect.s3.S3SinkConnector
tasks.max=1
topics=nginx-topic,lite-nginx-topic

s3.region=us-west-2
s3.bucket.name=kafka-bak-s3-us-west-2
flush.size=100000
rotate.schedule.interval.ms=3600000

storage.class=io.confluent.connect.s3.storage.S3Storage
format.class=io.confluent.connect.s3.format.json.JsonFormat
schema.generator.class=io.confluent.connect.storage.hive.schema.TimeBasedSchemaGenerator
partitioner.class=io.confluent.connect.storage.partitioner.TimeBasedPartitioner

schema.compatibility=NONE
partition.duration.ms=60000
path.format=YYYY/MM/dd
locale=en
timezone=UTC

The data on s3:
"{\\"id\\":\\"6baa2977ae5d121efb4f163e963db177\\",\\"host\\":\\"10.10.0.246\\",\\"name\\":\\"nginx\\",\\"family\\":\\"webapp-m\\",\\"task\\":\\"webapp-m:84\\",\\"cid\\":\\"722472e97ad1a43a248f57b69f1edc1ecb9a4b4ccf9d2826fa9d74687241de1b\\",\\"timestamp\\":\\"2017-09-02T15:45:23.290902089Z\\",\\"log_type\\":1,\\"raw\\":\\"\\",\\"log\\":{\\"body_bytes_sent\\":\\"43\\",\\"http_cookie\\":\\"\\",\\"http_referrer\\":\\"\\",\\"http_user_agent\\":\\"Mozilla/5.0 (Linux; Android 4.4.2; SM-G386T Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36\\",\\"level\\":\\"info\\",\\"process\\":\\"7\\",\\"remote_addr\\":\\"\\",\\"remote_user\\":\\"\\",\\"request_length\\":\\"1722\\",\\"request_method\\":\\"POST\\",\\"request_time\\":\\"0.023\\",\\"status\\":\\"200\\",\\"time\\":\\"1504367123.290\\",\\"time_iso8601\\":\\"2017-09-02T15:45:23+00:00\\",\\"upstream_cache_status\\":\\"\\"}}"

I want the data on s3:
{
  "id": "6baa2977ae5d121efb4f163e963db177",
  "host": "10.10.0.246",
  "name": "nginx",
  "family": "webapp-m",
  "task": "webapp-m:84",
  "cid": "722472e97ad1a43a248f57b69f1edc1ecb9a4b4ccf9d2826fa9d74687241de1b",
  "timestamp": "2017-09-02T15:45:23.290902089Z",
  "log_type": 1,
  "raw": "",
  "log": {
    "body_bytes_sent": "43",
    "http_cookie": "",
    "http_referrer": "",
    "http_user_agent": "Mozilla/5.0 (Linux; Android 4.4.2; SM-G386T Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36",
    "level": "info",
    "process": "7",
    "remote_addr": "",
    "remote_user": "",
    "request_length": "1722",
    "request_method": "POST",
    "request_time": "0.023",
    "status": "200",
    "time": "1504367123.290",
    "time_iso8601": "2017-09-02T15:45:23+00:00",
    "upstream_cache_status": ""
  }
}

**Comment by kkonstantine** [comment]
May I ask, how do you import your records to Kafka? Are you using `StringConverter` maybe?

**Comment by chuyouxin** [comment]
I confirm the data is json data in kafka, but when I export data from kafka to s3, the data is json string on s3, so I don't know why? please help me, thank you!

**Comment by jcustenborder** [comment]
@chuyouxin You need to post your worker config as well.

**Comment by kkonstantine** [comment]
This is probably an issue during import. Closing, since we don't have any updates for almost a year.
